### PR TITLE
[FIX] Access Restricted

### PR DESCRIPTION
**Pull request by tarzan0820**
fixes bug/ access error that occurs when non privileged users (employees) try to access the preference menu (top right hand)

### CODE REVIEW

**Comment by yelizariev** [comment]
I'll check it

**Comment by yelizariev** [comment]
I think more robust solution is  replace uid with SUPERUSER_ID in ``update_user_groups_view``

    def update_user_groups_view(self, cr, uid, context=None):
        self.pool['ir.config_parameter'].set_param(cr, SUPERUSER_ID, IR_CONFIG_NAME, uid, context=context)
        ctx = (context or {}).copy()
        ctx['access_restricted'] = 1
        return super(ResGroups, self).update_user_groups_view(cr, uid, context=ctx)

**Comment by yelizariev** [comment]
Let me know your thoughts and do you have time to check solution and update this PR

**Comment by tarzan0820** [comment]
@yelizariev any reason why you think the above fix is better? 

It may be unrelated but I get following error when I tried your method:

ValidateError

Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `in_group_25` does not exist

Error context:
View `res.users.groups`
[view_id: 156, xml_id: base.user_groups_view, model: res.users, parent_id: 153]

**Comment by yelizariev** [comment]
Probably, your error message is related to update you made before switching to my method. Also, be sure that you changed only one uid: 
self.pool['ir.config_parameter'].set_param(cr, **SUPERUSER_ID**, IR_CONFIG_NAME, **uid**, context=context)

But anyway, when you skip calling ``update_user_groups_view``, you use view, that was created for another person ( ``if int(last_uid) != uid ``). This is why I have bad feeling about such solution.

**Comment by yelizariev** [comment]
@tarzan0820 do you have a chance to review my comment? I confirm the bug and would like to fix it asap

**Comment by tarzan0820** [comment]
@yelizariev I only changed SUPERUSER_ID is one place (as per your instructions). Also I can confirm that the bug "in_group_x does not exist" (where x changes) was a commonly occurring error that I encountered even before I made the update.... I had to update the base addon each time that error came up. Haven't encountered it since I made the fix I am trying to merge

**Comment by yelizariev** [comment]
ok, let's try you solution. Thank you.

**Pull request merged**
